-- GEOSPAIN_COMUNIDADES
CREATE TABLE GEOSPAIN_COMUNIDADES (
    ID          	NUMBER,
    LANG  			SMALLINT,
    NAME 			VARCHAR2(4000),
    CREATED_DATE    TIMESTAMP (6) DEFAULT SYSDATE,
    UPDATED_DATE    TIMESTAMP (6) DEFAULT SYSDATE,
    CONSTRAINT PK_GEOSPAIN_COMUNIDADES PRIMARY KEY (ID, LANG)
);

CREATE SEQUENCE SEQ_GEOSPAIN_COMUNIDADES START WITH 1 INCREMENT BY 1;

INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 1, 'Andalusia', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 1, 'Aragó', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 1, 'Principat d''Astúries', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 1, 'Illes Balears', SYSDATE, SYSDATE);

INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 2, 'CANARIAS', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 2, 'CANTABRIA', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 2, 'CASTILLA-LA MANCHA', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 2, 'CASTILLA Y LEÓN', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 2, 'CATALUÑA', SYSDATE, SYSDATE);

INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 3, 'COMUNIDAD VALENCIANA', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 3, 'EXTREMADURA', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 3, 'GALICIA', SYSDATE, SYSDATE);
INSERT INTO GEOSPAIN_COMUNIDADES (ID, LANG, NAME, CREATED_DATE, UPDATED_DATE) VALUES (SEQ_GEOSPAIN_COMUNIDADES.nextval, 3, 'LA RIOJA', SYSDATE, SYSDATE);
